### PR TITLE
Added polish translation

### PR DESCRIPTION
**Pull request by mmarusiak**
Added polish translation based on english and spanish translation of application,

### CODE REVIEW

**Comment by mmarusiak** [comment]
Only things I;m not sure is line 417 in ``pl.po`` - hat translation. I'm not sure what does it exactly mean, so I just tried to connect spanish and english translation to polish.

**Comment by mmarusiak** [comment]
Also I'm not sure if beginning of the ``pl.po`` file is in in expected format - I just copied spanish version of it and changed a bit :)

**Comment by berarma** [comment]
The HAT is the D-Pad in some wheels.

**Comment by mmarusiak** [comment]
> The HAT is the D-Pad in some wheels.

Could you provide some example wheels that has HAT as D-Pad? I don't see anything when I'm looking for it, is it even translatable?

**Comment by berarma** [comment]
> > The HAT is the D-Pad in some wheels.
> 
> Could you provide some example wheels that has HAT as D-Pad? I don't see anything when I'm looking for it, is it even translatable?

I wouldn't translate it. The G29 and G920 have a D-Pad in the wheel.

**Comment by mmarusiak** [comment]
I think that's all that should be translated.

**Comment by berarma** [comment]
Please, could you redo these commits changing only the required files (LINGUAS and pl.po)?

**Comment by mmarusiak** [comment]
> Please, could you redo these commits changing only the required files (LINGUAS and pl.po)?

Of course, will do it on a Friday.

**Pull request merged**
