### PR TITLE
Add advanced_mode toggle for thrustmaster t300rs

### PR DESCRIPTION
**Pull request by ReazerDev**
Add a button to toggle between the normal t300rs mode and the advanced Ferrari F1 mode.
Add the Ferrari F1 Wheel to devices.

This is based on this branch in the driver: https://github.com/Kimplul/hid-tmff2/tree/adv and this issue https://github.com/Kimplul/hid-tmff2/issues/28

Context:
If you have the [Ferrari F1 Wheel Add On](https://shop.thrustmaster.com/de_de/ps3/ferrari-f1-wheel-add-on.html), the Windows driver allows you to switch to an "advanced" mode, which enables a few more buttons on the wheel.
The change in the driver and in this PR replicate the Windows driver's behaviour

### CODE REVIEW

**Comment by berarma** [comment]
I see you create a thread to change modes because I guess it's slow and blocks the UI. The same happens when changing compatbility modes in a Logitech wheel. I prefer to block the UI so the user can't change settings until the wheel is ready again. Maybe I should show a wait message when this happens.

@Kimplul: since there's already a compatibility mode implemented in Oversteer, would it be asking to much to change the implementation in your driver to mimic the one in the Logitech drivers?

The `alternate_modes` file for my wheel looks like this:

```
native: G29 Racing Wheel *
DF-EX: Driving Force / Formula EX
DFP: Driving Force Pro
G25: G25 Racing Wheel
DFGT: Driving Force GT
G27: G27 Racing Wheel
G29: G29 Racing Wheel *
```

Each line has the format `ID: Label`. Currently, I ignore lines where ID is `native` because it isn't really a mode, it's only telling us which mode is native. The line that has an asterisk is the current mode. Writing one of the IDs back in the file changes the mode.

This would make it easier to add more wheels that have several modes and adding modes to existing wheels. Since mode switching usually takes some time and the wheel is not responding I would add a wait message that would work for any wheel.

It's more work now but it's less code and less work in the future if we keep adding wheels. The interface would look cleaner without wheel specific settings that are duplicated.

It's not hard to implement in the driver and the code is reusable for more wheel models. You can see [how the Logitech driver implements it](https://github.com/berarma/new-lg4ff/blob/c329bb37c081c505a74540993a9ea6416fecfe06/hid-lg4ff.c#L1450). I didn't write it, this implementation is also used in the mainline kernel module. How do you feel about this?

**Comment by Kimplul** [comment]
Sure, I'll give it a go. In the example you gave, there's two stars, I suppose because the wheel can 'emulate' itself? In the T300, there's only two modes that I'm aware of, 'F1' and 'native', would using just one star work?

Something like
```
native: T300RS base *
F1: T300RS with F1 wheel addon
```
and
```
native: T300RS base
F1: T300RS with F1 wheel addon *
```

**Comment by Kimplul** [comment]
Alright, quick test seems to show the mode selector working, only thing is the T300RS doesn't actually do anything unless a specific wheel addon is installed on the wheel. This could be a bit misleading, as the alternate mode still shows up in Oversteer but applying it doesn't do anything. The easiest way around this that I can think of is to check which attachment the wheel has, I think I know how to read it at this point but I don't know all attachment IDs. I know @ReazerDev 's attachment showed up with id `0x03` whereas a default wheel is `0x06`, but there could be other ones I don't know about. I guess the best way forward is to only allow `0x03` to switch modes and add more attachments if someone happens to own one and opens up an issue about it?

**Comment by berarma** [comment]
I didn't make it clearly enough. I'm ignoring lines starting with `native` because it's not really a working mode. The asterisk in the `native` line is useless too.

Your file should be something like this:

```
base: T300RS base *
F1: T300RS with F1 wheel addon
```

or

```
base: T300RS base
F1: T300RS with F1 wheel addon *
```

when the F1 wheel is enabled.

Feel free to use the ids that you want but don't use `native`.

I think it's required to know which attachments are available to correctly handle the modes. You could also show all available modes and let the user try them and see, but I find this confusing. Ideally, the file should only exist when the wheel supports switching modes. I think having `alternate_modes` with just one mode line is also confusing.

> I guess the best way forward is to only allow `0x03` to switch modes and add more attachments if someone happens to own one and opens up an issue about it?

If all the attachments can switch modes with the same command we could have just two modes for all attachments: "standard mode" and "advanced mode". In case different attachments need different switch commands or if it's required to show a better label for the attachment then I'd do as you say.

**Comment by Kimplul** [comment]
Right, gotcha, thanks for the clarification.

> I think having alternate_modes with just one mode line is also confusing.

Maybe it's a bit excessive, yeah. Still, I think of it as 'this device supports alternate modes, but your configuration doesn't allow for them', whereas a greyed-out box is 'not supported at all'. In either case it would probably be best to explain whatever behaviour we're going with, in case somebody happens to have an attachment that should get special treatment and is confused as to why it isn't.

> If all the attachments can switch modes with the same command we could have just two modes for all attachments: "standard mode" and "advanced mode". In case different attachments need different switch commands or if it's required to show a better label for the attachment then I'd do as you say.

The problem is that I just don't know at the moment, the F1 attachment is the only one that someone (in this case @ReazerDev, thanks again) has contacted me about. I suspect assuming the worst is the 'safest' thing to do, at least any other attachments that get brought up will be easier to handle with different switch commands.

I had a look through the T300RS manual (as well as some of their wheel addon manuals)  but couldn't find any info on which attachments come with what modes, I suspect you sort of find out in the Thrustmaster configuration utility.

I did notice that they claim the T300RS shows up in most games as T500RS, but then five lines later they say it shows up in most games as a T300RS. Pretty funny.

**Comment by berarma** [comment]
> Maybe it's a bit excessive, yeah. Still, I think of it as 'this device supports alternate modes, but your configuration doesn't allow for them', whereas a greyed-out box is 'not supported at all'. In either case it would probably be best to explain whatever behaviour we're going with, in case somebody happens to have an attachment that should get special treatment and is confused as to why it isn't.

I think it's a perfectly valid point of view. I'll leave those details to you, I only wanted to make sure you understood how it's working. That way you have some control on how Oversteer shows that setting so I hope you can better handle the unknowns.

**Comment by berarma** [comment]
Superseded by changes in the driver.

**Pull request closed without merging**
