### PR TITLE
Add PIDs for more Fanatec devices

### PR DESCRIPTION
**Pull request by gotzl**

### CODE REVIEW

**Comment by berarma** [comment]
That's great, thanks!

**Comment by 24788329** [comment]
Hello and thank you for quickly adding the GT DD Pro to Oversteer. I reinstalled with the updated `berarma:master` files, and Oversteer now sees the wheel in PC native mode (red). However, it also shows the following error: "you don't have the required permission to change your wheel settings."

When using the wheel in PC compatibility mode (yellow), Oversteer starts normally without display the above error. I followed the uninstall/update procedure in the README, and also tried manually copying the udev rules. A reboot or udev reload command does not fix it. 

Am I missing something or should I be trying something else?

**Comment by berarma** [comment]
This PR hasn't added any udev rules for thw wheels. We'll need to add them. Do you know which settings are supported by the driver?

@gotzl, could you make a new PR with the needed PR rule?

**Comment by 24788329** [comment]
In both PC compatibility and PC native modes, the [colored 5-way d-pads](https://fanatec.com/media/image/dc/2b/05/Product_thumbnail_GT_DD_PRO_composition_600x600.jpg) on the GT DD Pro steering wheel do not work in ACC and do not register button presses in Oversteer. All of the other regular non-colored buttons work and register presses fine.

Let me know if there are other settings you want checked.

**Comment by berarma** [comment]
> In both PC compatibility and PC native modes, the [colored 5-way d-pads](https://fanatec.com/media/image/dc/2b/05/Product_thumbnail_GT_DD_PRO_composition_600x600.jpg) on the GT DD Pro steering wheel do not work in ACC and do not register button presses in Oversteer. All of the other regular non-colored buttons work and register presses fine.
> 
> Let me know if there are other settings you want checked.

You should use `evtest` to identify the events corresponding to those controls. Please, create new issues for that.

**Pull request merged**
