### PR TITLE
Fix wmclass in desktop file

### PR DESCRIPTION
**Pull request by BlueManCZ**
Desktop WMClass has changed from "Oversteer" to "oversteer" and now the application icon for running instance is not displayed correctly. This fixes it.

obrazek

### CODE REVIEW

**Comment by BlueManCZ** [comment]
Good question. I did not really investigate it further, but the window manager now reports that the window has WMClass="oversteer". It may be a few months old change. What does it report in your case?

**Comment by berarma** [comment]
It works like it should in my system. The window has `WM_CLASS(STRING) = "oversteer", "Oversteer"`.

These are the instance and class names following [ICCCM](https://tronche.com/gui/x/icccm/sec-4.html#WM_CLASS) conventions.

I didn't know the details about this and might still be missing something, but it looks like your WM isn't following the general conventions. If it worked before then it could be some recent bug. Can you check with your distro?

Can you share your distro and WM for reference?

Thanks.

**Comment by BlueManCZ** [comment]
Alright, I investigated this further. It happens only on Wayland. It doesn't happen on X11. This is Gnome with X11:



And this is the same Gnome with Wayland:



I tested that switching StartupWMClass to "oversteer" works correctly on both systems.

**Comment by berarma** [comment]
This is a note for my future self.

It seems Wayland doesn't use WMCLASS anymore, it uses AppId instead. The reason for this change isn't clear as it seems to break compatibility. Removing the StartupWMClass line works for me on X11 but not on Wayland, that's weird. Uppercase id works on X11 but not on Wayland, and lowercase id works on both. I'll merge based on test results without fully understanding the change.

**Pull request merged**
