### PR TITLE
support for T300RS

### PR DESCRIPTION
**Pull request by Kimplul**
Here is the aforementioned code that adds in support for the T300RS.

### CODE REVIEW

**Comment by berarma** [comment]
I would merge this in an experimental branch so I can make some more changes so that the code is less Logitech-specific, or we could directly merge it into master but then I wouldn't change the name of the udev rules file just yet.

**Comment by Kimplul** [comment]
I'm guessing keeping the udev rules names for now is probably a better idea, I haven't yet had the time to check if other Thrustmaster wheels can easily be supported, and putting a lot of effort into making the program more generic for one wheel seems like a hassle.

**Comment by berarma** [comment]
So do you revert the change in the file name so that I can merge it to master?

**Comment by berarma** [comment]
It's merged. It's left like a new experimental feature and we'll keep working on it. I have no way to test it so I must rely on you or others.

**Pull request closed without merging**
